#!/bin/bash
for((i=1;i<6;i++))
do
for((s=4;s>=$i;s--))
do
echo -n " "
done
	for((r=1;r<=$i;r++))
	do
	echo -n "*"
	done
for((v=1;v<5;v++))
do
	echo -n "*"
	for((t=5;t<=10;t++))
do
        echo -n "*"
done
done
echo
done
