#!/bin/bash
#Marko Kaja IS116
for((number=1;number<4;number++))
do
cat  menu$number
done
echo "Please give a number (1-3)"
read number
case $number in
1)	
	
	echo -e "Stick to your ribs.\nWatch your cholesterol\n Enjoy your meal!" 
	;;
2)
	echo -e "British are comin\nEnjoy your meal!"
	;;
3)
	echo -e "Health foods..\n Dieting is so boring.\n Enjoy your meal!"
	;;
*)
	echo -e "Use only numbers 1-3"
	;;
esac
